### ISSUE TITLE
Undefined Function In the file

### ISSUE THREAD

**Issue by Narendra-027** [CyclicalCurriculum/Cyclical-Curriculum#1]
Hello,

First and foremost, I want to express my appreciation for the valuable work you have shared through your research paper and accompanying GitHub repository.

While attempting to reproduce the results presented in your paper, I encountered an issue. 
In the file `Trains.py`, line 66 there is use of a function `get_random_mixup` which is not defined in any of the files provided in the Repository.

I kindly request your assistance in resolving this issue. Could you please provide the correct function or update the code? It's hindering result reproduction.

**Comment by CyclicalCurriculum** [comment]
Hello, that function is not used in the work in the article. It was deleted during the research phase. You can use the code under the examples folder to simply try the method on a new or existing dataset.
